/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectStatus = IDL.Variant({
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'planning' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'toDo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'projectIds' : IDL.Vec(IDL.Nat),
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'clientId' : IDL.Nat,
  'taskIds' : IDL.Vec(IDL.Nat),
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'budget' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'assignee' : IDL.Text,
  'title' : IDL.Text,
  'dueDate' : IDL.Text,
  'projectId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, ProjectStatus, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, TaskStatus],
      [IDL.Nat],
      [],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectStatus = IDL.Variant({
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'planning' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'toDo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'projectIds' : IDL.Vec(IDL.Nat),
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'clientId' : IDL.Nat,
    'taskIds' : IDL.Vec(IDL.Nat),
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'budget' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'assignee' : IDL.Text,
    'title' : IDL.Text,
    'dueDate' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  
  return IDL.Service({
    'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ProjectStatus,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, TaskStatus],
        [IDL.Nat],
        [],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'updateProjectStatus' : IDL.Func([IDL.Nat, ProjectStatus], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };