/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
  'projectIds' : Array<bigint>,
}
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'clientId' : bigint,
  'taskIds' : Array<bigint>,
  'endDate' : string,
  'name' : string,
  'description' : string,
  'budget' : bigint,
  'startDate' : string,
}
export type ProjectStatus = { 'completed' : null } |
  { 'inProgress' : null } |
  { 'planning' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : string,
  'title' : string,
  'dueDate' : string,
  'projectId' : bigint,
}
export type TaskStatus = { 'done' : null } |
  { 'toDo' : null } |
  { 'inProgress' : null };
export interface _SERVICE {
  'createClient' : ActorMethod<[string, string, string], bigint>,
  'createProject' : ActorMethod<
    [string, string, ProjectStatus, string, string, bigint, bigint],
    bigint
  >,
  'createTask' : ActorMethod<
    [bigint, string, string, string, TaskStatus],
    bigint
  >,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getClient' : ActorMethod<[bigint], Client>,
  'getProject' : ActorMethod<[bigint], Project>,
  'getTask' : ActorMethod<[bigint], Task>,
  'updateProjectStatus' : ActorMethod<[bigint, ProjectStatus], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];